config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :enrollments do
    collection do
      get 'search'
    end
  end

  resources :students do
    collection do
      get 'search'
    end
  end

  resources :sections do
    collection do
      get 'search'
    end
  end

  resources :courses do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'courses#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<% unless flash.empty? %>
  <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
  </script>
<% end %>

  <head>
  <style>
    ul {
      -webkit-appearance: button;
      -moz-appearance: button;
      appearance: button;

      display:inline-block;
      min-width: 60px;
      padding: 5px 10px;
      text-align: center;
      text-decoration: none;
      color:grey;
    }
  </style>
    <nav>
      <div class="nav navbar">
        <ul><%=link_to "Courses", courses_path%></ul>
        <ul><%=link_to "Sections", sections_path%></ul>
        <ul><%=link_to "Students", students_path%></ul>
        <ul><%=link_to "Enrollments", enrollments_path%></ul>
      </div>
    </nav>

    <title>Course Tracker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
    <style>
      body {
        background: lightcyan;
      }
    </style>
  </body>
</html>